server:
  port: 8088
  
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

spring:
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: microcliente
          uri: lb://MICROCLIENTE
          predicates:
            - Path=/clientepersonal/**
